// <auto-generated />
using BTAPLON.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

#nullable disable

namespace BTAPLON.Migrations
{
    [DbContext(typeof(EduDbContext))]
    [Migration("20251101120000_AddNotificationReceipts")]
    partial class AddNotificationReceipts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new EduDbContextModelSnapshot().PopulateModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}