// <auto-generated />
using System;
using BTAPLON.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTAPLON.Migrations
{
    [DbContext(typeof(EduDbContext))]
    partial class EduDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTAPLON.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("ClassID");

                    b.ToTable("Assignments");
                });
            modelBuilder.Entity("BTAPLON.Models.Choice", b =>
            {
                b.Property<int>("ChoiceID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceID"));

                b.Property<bool>("IsCorrect")
                    .HasColumnType("bit");

                b.Property<int>("QuestionID")
                    .HasColumnType("int");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("ChoiceID");

                b.HasIndex("QuestionID");

                b.ToTable("Choices");
            });

            modelBuilder.Entity("BTAPLON.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("BTAPLON.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("BTAPLON.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("ClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });
            modelBuilder.Entity("BTAPLON.Models.Exam", b =>
            {
                b.Property<int>("ExamID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamID"));

                b.Property<int>("ClassID")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CreatorID")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("DurationMinutes")
                    .HasColumnType("int");

                b.Property<DateTime?>("EndTime")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsPublished")
                    .HasColumnType("bit");

                b.Property<bool>("PreventBackNavigation")
                    .HasColumnType("bit");

                b.Property<DateTime?>("PublishedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("StartTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("ExamID");

                b.HasIndex("ClassID");

                b.HasIndex("CreatorID");

                b.ToTable("Exams");
            });

            modelBuilder.Entity("BTAPLON.Models.ExamSubmission", b =>
            {
                b.Property<int>("ExamSubmissionID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamSubmissionID"));

                b.Property<string>("AnswersJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ExamID")
                    .HasColumnType("int");

                b.Property<bool>("IsFinalized")
                    .HasColumnType("bit");

                b.Property<double?>("Score")
                    .HasColumnType("float");

                b.Property<DateTime>("StartedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("StudentID")
                    .HasColumnType("int");

                b.Property<DateTime?>("SubmittedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("TeacherFeedback")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ExamSubmissionID");

                b.HasIndex("ExamID");

                b.HasIndex("StudentID");

                b.ToTable("ExamSubmissions");
            });

            modelBuilder.Entity("BTAPLON.Models.Question", b =>
            {
                b.Property<int>("QuestionID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.Property<int>("ExamID")
                    .HasColumnType("int");

                b.Property<bool>("IsMultipleChoice")
                    .HasColumnType("bit");

                b.Property<double>("Points")
                    .HasColumnType("float");

                b.Property<string>("Prompt")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.HasKey("QuestionID");

                b.HasIndex("ExamID");

                b.ToTable("Questions");
            });
            modelBuilder.Entity("BTAPLON.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionID"));

                    b.Property<int>("AssignmentID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionID");

                    b.HasIndex("AssignmentID");

                    b.HasIndex("StudentID");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("BTAPLON.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                });

            modelBuilder.Entity("BTAPLON.Models.Assignment", b =>
                {
                    b.HasOne("BTAPLON.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });
            modelBuilder.Entity("BTAPLON.Models.Choice", b =>
            {
                b.HasOne("BTAPLON.Models.Question", "Question")
                    .WithMany("Choices")
                    .HasForeignKey("QuestionID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Question");
            });
            modelBuilder.Entity("BTAPLON.Models.Class", b =>
                {
                    b.HasOne("BTAPLON.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BTAPLON.Models.Course", b =>
                {
                    b.HasOne("BTAPLON.Models.User", "Teacher")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BTAPLON.Models.Enrollment", b =>
                {
                    b.HasOne("BTAPLON.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAPLON.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BTAPLON.Models.Exam", b =>
            {
                b.HasOne("BTAPLON.Models.Class", "Class")
                    .WithMany("Exams")
                    .HasForeignKey("ClassID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BTAPLON.Models.User", "Creator")
                    .WithMany("ExamsCreated")
                    .HasForeignKey("CreatorID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Class");

                b.Navigation("Creator");
            });

            modelBuilder.Entity("BTAPLON.Models.ExamSubmission", b =>
            {
                b.HasOne("BTAPLON.Models.Exam", "Exam")
                    .WithMany("Submissions")
                    .HasForeignKey("ExamID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BTAPLON.Models.User", "Student")
                    .WithMany("ExamSubmissions")
                    .HasForeignKey("StudentID")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Exam");

                b.Navigation("Student");
            });

            modelBuilder.Entity("BTAPLON.Models.Question", b =>
            {
                b.HasOne("BTAPLON.Models.Exam", "Exam")
                    .WithMany("Questions")
                    .HasForeignKey("ExamID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Exam");
            });
            modelBuilder.Entity("BTAPLON.Models.Submission", b =>
                {
                    b.HasOne("BTAPLON.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAPLON.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BTAPLON.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BTAPLON.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("BTAPLON.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });
            modelBuilder.Entity("BTAPLON.Models.Exam", b =>
            {
                b.Navigation("Questions");

                b.Navigation("Submissions");
            });

            modelBuilder.Entity("BTAPLON.Models.Question", b =>
            {
                b.Navigation("Choices");
            });
            modelBuilder.Entity("BTAPLON.Models.User", b =>
                {
                    b.Navigation("CoursesTaught");

                    b.Navigation("Enrollments");
                    b.Navigation("ExamSubmissions");

                    b.Navigation("ExamsCreated");


                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
